### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [serobj/serobj-python#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.0.2. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary serobj -w /tmp/ext serobj==0.0.2
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting serobj==0.0.2
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/42d/7bf3c731b1b76/serobj-0.0.2.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-fwkjkham/serobj/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-fwkjkham/serobj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-fwkjkham/serobj/pip-egg-info
         cwd: /tmp/pip-wheel-fwkjkham/serobj/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-fwkjkham/serobj/setup.py", line 41, in <module>
        install_requires=read("requirements.txt").strip().split("\n"),
      File "/tmp/pip-wheel-fwkjkham/serobj/setup.py", line 23, in read
        file = open(path, encoding="utf-8")
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-fwkjkham/serobj/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
There's no source here?

**Comment by vadzimsharai** [comment]
Hi, @thatch !

Thank you)

now you can install 0.0.3 version
`/tmp/venv/bin/pip3 wheel --no-binary serobj -w /tmp/ext serobj==0.0.3`

Also I have added the source code
